log_level: debug
log_dir_name: log
log_file_name: ionian.log
kafka_brokers:
  - 192.168.0.31:9092
  - 192.168.0.32:9092
  - 192.168.0.33:9092
collector_waiting_term_seconds: 2
consumer_waiting_term_seconds: 5
crawler_waiting_term_seconds: 1
db_writer_size: 20
data_root_path: ./data/raw/text
news_topic_name: news_info
news_raw_contents_topic_name: news_raw_contents
news_raw_contents_stream_enable: True
pachd_host: 192.168.0.33
pachd_port: 30650
