log_level: debug
log_dir_name: log
log_file_name: ionian.log
kafka_brokers:
  - 192.168.0.31:9092
consumer_waiting_term_seconds: 5
parser_waiting_term_seconds: 1
db_writer_size: 20
daum_news_topic_name: daum_news_info